obj-$(CONFIG_TI_TILER) += tcm/

obj-$(CONFIG_TI_TILER) += tiler.o
tiler-objs = tiler-geom.o tiler-main.o tiler-iface.o tiler-reserve.o tmm-pat.o

obj-$(CONFIG_TI_TILER) += tiler_dmm.o
tiler_dmm-objs = dmm.o

